// Folder tree, baked. Reads manifests/<bucket>.tsv (key \t size) and writes
// src/data/folder-tree.json — every folder path per bucket plus file count and
// bytes — so the admin's column browser draws folders instantly, with no list
// fetch and no spinner (user ruling 2026-08-27). Regenerated by
// `pnpm media-manifest` (which also refreshes the TSVs) or `pnpm folder-tree`.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const ROOT = new URL('../', import.meta.url);
const BUCKETS = ['r2', 'b2', 'b2vault'];

export function buildTree() {
  const tree = {};
  for (const id of BUCKETS) {
    const path = new URL(`manifests/${id}.tsv`, ROOT);
    if (!existsSync(path)) continue;
    const folders = new Set();
    /* PER-FOLDER COUNTS (ColumnBrowserMobileViews, 2026-09-04): the DS's `folderMeta`
     * seam asks a folder for its own meta line and deliberately does NOT count —
     * counting `objects` by prefix is O(n) per folder, and this file is already a
     * whole-bucket pass. So the pass carries the tally: every ancestor of a key gets
     * that key's size added, which makes a folder's number RECURSIVE — what the folder
     * holds in total, not just its direct children, which is what a file browser shows. */
    const counts = {};
    let files = 0;
    let bytes = 0;
    for (const line of readFileSync(path, 'utf8').split('\n')) {
      if (!line) continue;
      const [key, size] = line.split('\t');
      const n = Number(size) || 0;
      files += 1;
      bytes += n;
      const parts = key.split('/');
      for (let i = 1; i < parts.length; i++) {
        const dir = parts.slice(0, i).join('/') + '/';
        folders.add(dir);
        const c = (counts[dir] ??= { files: 0, bytes: 0 });
        c.files += 1;
        c.bytes += n;
      }
    }
    tree[id] = { folders: [...folders].sort(), counts, files, bytes };
  }
  const out = new URL('src/data/folder-tree.json', ROOT);
  writeFileSync(out, JSON.stringify(tree));
  return tree;
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split('/').pop())) {
  const t = buildTree();
  for (const [id, v] of Object.entries(t)) console.log(`${id}: ${v.folders.length} folders · ${v.files} files`);
}
